# Generated by Django 4.1.7 on 2023-06-09 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='resultado',
            name='nombre',
            field=models.CharField(default='Valor predeterminado', max_length=255),
        ),
    ]
