# Generated by Django 4.1.7 on 2023-06-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_resultado_fecha_resultado_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
