# Generated by Django 4.1.7 on 2023-06-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_alter_resultado_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='texto',
            field=models.CharField(max_length=300),
        ),
    ]
