# Generated by Django 4.1.7 on 2023-06-10 22:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_alter_resultado_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('contenido', models.CharField(max_length=400)),
                ('is_completed', models.BooleanField(default=False)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_actual', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.resultado')),
            ],
        ),
    ]
