# Generated by Django 4.1.7 on 2023-06-14 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.actividad')),
            ],
        ),
    ]
