# Generated by Django 4.1.7 on 2023-06-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
