# Generated by Django 4.1.7 on 2023-06-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0007_seccion_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='avance',
            field=models.IntegerField(default=False),
        ),
    ]
