# Generated by Django 4.1.7 on 2023-06-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0008_seccion_avance'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='contenido',
            field=models.CharField(default=False, max_length=400),
        ),
    ]
