# Generated by Django 4.1.7 on 2023-06-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0009_seccion_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fecha',
            field=models.IntegerField(default=False),
        ),
    ]
