# Generated by Django 4.1.7 on 2023-06-19 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0011_avance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dificultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=400)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=400)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.actividad')),
            ],
        ),
    ]
