# Generated by Django 4.1.7 on 2023-06-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0014_delete_cambio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avance',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='dificultad',
            name='actividad',
        ),
        migrations.DeleteModel(
            name='Alternativa',
        ),
        migrations.DeleteModel(
            name='Avance',
        ),
        migrations.DeleteModel(
            name='Dificultad',
        ),
    ]
