# Generated by Django 4.1.7 on 2023-06-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0016_dificultad_avance_alternativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='fecha',
        ),
    ]
