# Generated by Django 4.1.7 on 2023-06-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0017_remove_actividad_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='avance',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dificultad',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='texto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='contenido',
            field=models.TextField(),
        ),
    ]
