# Generated by Django 4.1.7 on 2023-06-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0018_alter_actividad_contenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='fecha_vencimiento_seccion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
