# Generated by Django 4.1.7 on 2023-07-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0021_resultado_promedio_avance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumplida', models.TextField(blank=True)),
                ('proceso', models.TextField(blank=True)),
                ('urgente', models.TextField(blank=True)),
            ],
        ),
    ]
