# Generated by Django 4.1.7 on 2023-07-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0022_tiempo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tiempo',
        ),
    ]
