# Generated by Django 4.1.7 on 2023-07-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0024_tiempo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tiempo',
        ),
    ]
