# Generated by Django 4.1.7 on 2023-09-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0029_proyecto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
