# Generated by Django 4.1.7 on 2023-09-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0032_resultado2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resultado2',
        ),
    ]
