# Generated by Django 4.1.7 on 2023-09-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0034_resultado2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativa',
            name='dificultad',
        ),
        migrations.RemoveField(
            model_name='avance',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='cumplido',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='dificultad',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='resultado2',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='urgente',
            name='actividad',
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.DeleteModel(
            name='Alternativa',
        ),
        migrations.DeleteModel(
            name='Avance',
        ),
        migrations.DeleteModel(
            name='Cumplido',
        ),
        migrations.DeleteModel(
            name='Dificultad',
        ),
        migrations.DeleteModel(
            name='Proceso',
        ),
        migrations.DeleteModel(
            name='Resultado',
        ),
        migrations.DeleteModel(
            name='Resultado2',
        ),
        migrations.DeleteModel(
            name='Seccion',
        ),
        migrations.DeleteModel(
            name='Urgente',
        ),
    ]
